### ISSUE TITLE
'kotlin.UninitializedPropertyAccessException: lateinit property query has not been initialized' exception

### ISSUE THREAD

**Issue by jayeshbabuav** [chintan369/Geo-FireStore-Query#10]
When I run the following code:
`GeoQuery geoQuery = new GeoQuery()
                .whereNearToLocation(centerLocation, distanceForRadius, "extraG")
                .limit(20);`
I am getting this exception:
`java.lang.RuntimeException: Unable to resume activity {in.hashcoder.dishyumm/in.hashcoder.dishyumm.home.home_fragments.LocationDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property query has not been initialized
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3993)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4025)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property query has not been initialized
        at com.ckdroid.geofirequery.GeoQuery.whereNearToLocation(GeoQuery.kt:168)
        at in.hashcoder.dishyumm.home.home_fragments.LocationDetailsActivity.onResume(LocationDetailsActivity.java:205)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7557)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3985)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4025) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) `

**Comment by jayeshbabuav** [comment]
I forgot to add `.collection('collectionname')` before `.whereNearToLocation()`. That was the reason for the exception.
